{
 "title": "Pizza-Service Prod",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pizza_latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza latency"
    },
    {
     "expr": "rate(service_latency_milliseconds_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Revenue"
    },
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizzas_failed_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizzas failed"
    }
   ]
  },
  {
   "title": "CPU/Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(auth_attempts_success_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_attempts_fail_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(get_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(put_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(post_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(delete_requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    },
    { "expression": "$A + $B + $C + $D", "type": "math" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "active_users{source=\"jwt-pizza-service\"}",
     "legendFormat": "active_users"
    }
   ]
  }
 ]
}